config/routes.rb
Finance::Application.routes.draw do
  get "membres" => "profiltotals#index"
  get "profiltotals/show"
  get "users/index"
  get "users/show"
  get "accueil" => "accueil#index"
  get "accueil/show"
  get "cours/index"
  get "cours/show"
  get "bourse" => "bourses#index"
  get "bourses/show"
  devise_for :users, :controllers => { :registrations => "users" }
  resources :profils
  get "cours" => "profils#index"
  root "accueil#index"

end

app/models/cours.rb
class Cours < ActiveRecord::Base
end

app/models/profil.rb
class Profil < ActiveRecord::Base
  has_attached_file :cours
  validates_attachment_content_type :cours, :content_type => ["application/pdf"]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    has_attached_file :avatars,{
    :styles => {
      :thumb => ["50x50#", :png],
      :medium => ["100x100#", :png],
      :large => ["300x300>", :png]
    },
    :convert_options => {
      :thumb => "-gravity Center -crop 50x50+0+0",
      :thumb => "-gravity Center -crop 100x100+0+0",
    }
  }
  has_attached_file :cvs
  validates_attachment_content_type :avatars, :content_type => ["image/jpg", "image/jpeg", "image/png"]
  validates_attachment_content_type :cvs, :content_type => ["application/pdf","application/pdf","application/pdf"]

   
end

app/controllers/accueil_controller.rb
class AccueilController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :firstname, :username, :lastname, :avatars, :cvs, :role) }
  devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :firstname, :username, :lastname, :avatars, :cvs, :role) }

    
  end
end

app/controllers/bourses_controller.rb
class BoursesController < ApplicationController
  before_action :authenticate_user!
  def index
  end

  def show
  end
end

app/controllers/cours_controller.rb
class CoursController < ApplicationController
  def index
  end

  def show
  	@profil=Profil.where(id: params[:path])
    render :layout => false
  end
end

app/controllers/profils_controller.rb
class ProfilsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_profil, only: [:show, :edit, :update, :destroy]

  # GET /profils
  # GET /profils.json
  def index
    @profiltotal = Profil.all
  end

  # GET /profils/1
  # GET /profils/1.json
  def show
  end

  # GET /profils/new
  def new
    @profil = Profil.new
  end

  # GET /profils/1/edit
  def edit
  end

  # POST /profils
  # POST /profils.json
  def create
    @profil = Profil.new(profil_params)

    respond_to do |format|
      if @profil.save
        format.html { redirect_to @profil, notice: 'Profil was successfully created.' }
        format.json { render action: 'show', status: :created, location: @profil }
      else
        format.html { render action: 'new' }
        format.json { render json: @profil.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profils/1
  # PATCH/PUT /profils/1.json
  def update
    respond_to do |format|
      if @profil.update(profil_params)
        format.html { redirect_to @profil, notice: 'Profil was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @profil.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profils/1
  # DELETE /profils/1.json
  def destroy
    @profil.destroy
    respond_to do |format|
      format.html { redirect_to profils_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profil
      @profil = Profil.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profil_params
      params.require(:profil).permit(:nom, :description , :cours)
    end
end

app/controllers/profiltotals_controller.rb
class ProfiltotalsController < ApplicationController
  def index
  	@profiltotal=User.all
  end

  def show
  	@profiltotal=User.where(id: params[:path])
  	render :layout => false
  end
end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController
  def update
    @user = User.find(current_user.id)

    successfully_updated = if needs_password?(@user, params)
      @user.update_with_password(devise_parameter_sanitizer.sanitize(:account_update))
    else
      # remove the virtual current_password attribute
      # update_without_password doesn't know how to ignore it
      params[:user].delete(:current_password)
      @user.update_without_password(devise_parameter_sanitizer.sanitize(:account_update))
    end

    if successfully_updated
      set_flash_message :notice, :updated
      # Sign in the user bypassing validation in case his password changed
      sign_in @user, :bypass => true
      redirect_to after_update_path_for(@user)
    else
      render "edit"
    end
  end
  private

  # check if we need password to update user data
  # ie if password or email was changed
  # extend this as needed
  def needs_password?(user, params)
    user.email != params[:user][:email] ||
      params[:user][:password].present?
  end

end

app/helpers/accueil_helper.rb
module AccueilHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bourses_helper.rb
module BoursesHelper
end

app/helpers/cours_helper.rb
module CoursHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
end

app/helpers/profils_helper.rb
module ProfilsHelper
end

app/helpers/profiltotals_helper.rb
module ProfiltotalsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accueil/index.html.erb
<html dir="ltr" lang="fr-FR" class="js"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="UTF-8">
<title>Fiinance</title>

<!--[if IE]><![endif]-->
<link rel="shortcut icon" href="consely/favicon2.png" type="image/x-icon">
<link rel="stylesheet" href="/assets/consely.css" type="text/css" media="screen">
<link href='/assets/immersive-slider.css' rel='stylesheet' type='text/css'>
<script type="text/javascript" src="/assets/jquery.immersive-slider.js"></script>
</head>

<body id='home'>

        <div id='header'>
      
    </div>

<div id="gallerie" class="wrapper">
    <header>    
    <div class="main">
      <div class="page_container">
        <div id="immersive_slider">
          <div class="slide">
            <div class="content">

              <h2><a href="#" target="_blank">Hey ! I'm a paragraph</a></h2>
              <p>This is a great space to write long text about your company and your services. You can use this space to go into a little more detail about your company. Talk about your team and what services you provide. Tell your visitors the story of how you came up with the idea for your business and what makes you different from your competitors. Make your company stand out and show your visitors who you are.</p>
            </div>

            <div class="image">
              <a href="#" target="_blank">
                <img src="consely/conselyv2.png" alt="Slider 1">
              </a>
            </div>
          
          </div>
          
          <div class="slide">
            <div class="content">
              <h2><a href="#" target="_blank">Hey ! I'm the second paragraph</a></h2>
              <p>This is a great space to write long text about your company and your services. You can use this space to go into a little more detail about your company. Talk about your team and what services you provide. Tell your visitors the story of how you came up with the idea for your business and what makes you different from your competitors. Make your company stand out and show your visitors who you are.</p>
            </div>
            <div class="image">
             <a href="#" target="_blank"> <img src="consely/conselyv2.png" alt="Slider 1"></a>
            </div>
          </div>
          <div class="slide">
            <div class="content">
              <h2><a href="#" target="_blank">Hey ! I'm the third paragraph</a></h2>
              <p>This is a great space to write long text about your company and your services. You can use this space to go into a little more detail about your company. Talk about your team and what services you provide. Tell your visitors the story of how you came up with the idea for your business and what makes you different from your competitors. Make your company stand out and show your visitors who you are.</p>
            </div>
            <div class="image">
              <a href="#" target="_blank"><img src="consely/bourse.jpg" alt="Slider 1"></a>
            </div>
          </div>
          <div class="slide">
            <div class="content">
              <h2><a href="#" target="_blank">Hey ! I'm the fourth paragraph</a></h2>
              <p>This is a great space to write long text about your company and your services. You can use this space to go into a little more detail about your company. Talk about your team and what services you provide. Tell your visitors the story of how you came up with the idea for your business and what makes you different from your competitors. Make your company stand out and show your visitors who you are.</p>
            </div>
            <div class="image">
              <a href="#" target="_blank"><img src="consely/conselyv2.png" alt="Slider 1"></a>
            </div>
          </div>
          
          <a href="#" class="is-prev">&laquo;</a>
          <a href="#" class="is-next">&raquo;</a>
        </div>
      </div>
    </div>
    <div class="benefits">
      <div class="page_container">

      </div>
    </div>
    <script type="text/javascript">
      $(document).ready( function() {
        $("#immersive_slider").immersive_slider({
          container: ".main"
        });
      });

    </script>
  </br>
 </div>

      <div class = "bandeau1" >
        <img src ="/assets/bandeau.png" class="bandeauimage">
        <p class="bandeau"> This is a great space to write long text about your company and your services. You can use this space to go into a little more detail about your company. Talk about your team and what services you provide. Tell your visitors the story of how you came up with the idea for your business and what makes you different from your competitors. Make your company stand out and show your visitors who you are.</p>
      </div>
      <div class = "bandeau1" >
        <img src ="/assets/bandeau.png" class="bandeauimage">
        <p class="bandeau"> This is a great space to write long text about your company and your services. You can use this space to go into a little more detail about your company. Talk about your team and what services you provide. Tell your visitors the story of how you came up with the idea for your business and what makes you different from your competitors. Make your company stand out and show your visitors who you are.</p>
      </div>
      <div id="contacts" >
        <p id="textecontacts" class="bandeau">
          <br>This is a great space to write long text about your company and your services. You can use this space to go into a little more detail about your company. Talk about your team and what services you provide. Tell your visitors the story of how you came up with the idea for your business and what makes you different from your competitors. Make your company stand out and show your visitors who you are.

        </p>
      </br>
      </div>
</br>
      <div class = "bandeaunoir" >
        <img src ="/assets/bandeaunoir.png" class="bandeauimage2">
        <p class="texte"> This is a great space to write long text about your company and your services. You can use this space to go into a little more detail about your company. Talk about your team and what services you provide. Tell your visitors the story of how you came up with the idea for your business and what makes you different from your competitors. Make your company stand out and show your visitors who you are.</p>
        <hr width="30%" text-align="center"></hr>
         <p class="texte"> This is a great space to write long text about your company and your services. You can use this space to go into a little more detail about your company. Talk about your team and what services you provide. Tell your visitors the story of how you came up with the idea for your business and what makes you different from your competitors. Make your company stand out and show your visitors who you are.</p>



      </div>
      <div class = "bandeau2" >
        <img src ="/assets/bandeau.png" class="bandeauimage">
        <p class="bandeau"> This is a great space to write long text about your company and your services. You can use this space to go into a little more detail about your company. Talk about your team and what services you provide. Tell your visitors the story of how you came up with the idea for your business and what makes you different from your competitors. Make your company stand out and show your visitors who you are.</p>
        </br>
</br>
</br>
</br>
</br>
</br>
      </div>

app/views/accueil/show.html.haml
%h1 Accueil#show
%p Find me in app/views/accueil/show.html.haml

app/views/bourses/index.html.haml
%html
  %head
  %title Mon projet
  %link{:href => "//localhost:3000/assets/bourse.css", :rel => "stylesheet", :type => "text/css"}
    %body
      %div
        %iframe{:class => "bourse",:allowtransparency => "true", :frameborder => "0", :height => "580", :scrolling => "no", :src => "http://tools.fxempire.fr/live-charts.php?instrument=EUR%2FUSD&frequency=30_min&graph_type=candlestick&width=620&height=620&headline_color=082f60&text_color=333&bg_color=eeeeee&frame_color=ccc",:width => "620"}
        %div{:class=>"bourse"}
          %iframe{:id=>"analyse",:allowtransparency => "true", :frameborder => "0", :height => "320", :scrolling => "no", :src => "http://tools.fxempire.fr/technical-analysis.php?currency_pair=EUR%2FUSD&amp;time_frame=15_min&amp;width=450&amp;height=387&amp;tables%5Bnumeric%5D=1&amp;headline_color=082f60&amp;text_color=082f60&amp;bg_color=f5f5f5&amp;alt_row_color=E7E7E7&amp;frame_color=ccc", :width => "450"}
          %br
          =image_tag "bandeau.png", :width => "100%", :height=>"60px",:id=>"bandeau"
          %p{:id=>"cours"} Un soucis ? Venez consulter nos cours en ligne 
      %iframe{:class => "calendrier",:border => "0", :broder => "0", :frameborder => "0", :height => "360", :hspace => "0", :marginheight => "0", :marginwidth => "0", :src => "http://forex.fo/EconomicCalendar.php", :vspace => "0", :width => "89%"}
        


        

app/views/bourses/show.html.haml
%h1 Bourses#show
%p Find me in app/views/bourses/show.html.haml

app/views/cours/index.html.haml
%h1 Cours#index
%p Find me in app/views/cours/index.html.haml

app/views/cours/show.html.erb
<script type="text/javascript" src="assets/jquery.media.js"></script> 
<script> $(document).ready(function(){

  $('a.media').media({width:800, height:400});
});
</script>

<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @profil.first['nom'] %>
</p>

<p>
  <strong>Description:</strong>
  <%= @profil.first['description'] %>
</p>
<p>
<strong>Cours:</strong>
<div style="padding-left:7%;">
<a class="media" href= "<%=@profil.first.cours%>"></a>
</div>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Finance</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="navbar-text pull-right">
	<% if user_signed_in? %>
	  Logged in as <strong><%= current_user.email %></strong>.
	  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
	  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
	<% else %>
	  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
	  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
	<% end %>
<%= yield %>
<% if notice %>
	<p class="alert alert-notice"><%= notice %></p>
	<% end %>
	<% if alert %>
	<p class="alert alert-error"><%= alert %></p>
	<% end %>
</body>
</html>

app/views/profils/_form.html.erb
<%= form_for(@profil) do |f| %>
  <% if @profil.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profil.errors.count, "error") %> prohibited this profil from being saved:</h2>

      <ul>
      <% @profil.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %><br>
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :cours %><br>
    <%= f.file_field :cours %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profils/edit.html.erb
<h1>Editing profil</h1>

<%= render 'form' %>

<%= link_to 'Show', @profil %> |
<%= link_to 'Back', profils_path %>

app/views/profils/index.html.haml
%html
  %head
  %title Mon projet
  %link{:href => "//localhost:3000/assets/css.css", :rel => "stylesheet", :type => "text/css"}
    %body
      %div{:id =>"wrap", :align =>"center"}
        - @profiltotal.each do |profil|
          %div{:id => profil["id"], :class => "test"} 
            %p{:id=>"test"}
              = profil["nom"]
      %div{:id =>"fade"}
        %div{:id =>"pop-up"}
      
      :javascript
        $('#wrap div').click(function() {
          var thisID = $(this).attr('id');
          $.ajax({
            type:"Get",
            url:"/cours/show",
            data:{path:thisID},
            success: function(data){
              $("#pop-up").html(data);
              $("#fade").show();
              $("#pop-up").show();
              $("#fade").click(function(){
               $("#pop-up").hide();
               $("#fade").hide();
              });
              }
            ,
            error:function(data){
              console.log(data);
            }
          });
        });
        

app/views/profils/new.html.erb
<h1>New profil</h1>

<%= render 'form' %>

<%= link_to 'Back', profils_path %>

app/views/profils/show.html.erb
<script type="text/javascript" src="jquery.media.js"></script> 

<script> $(document).ready(function(){

  $('a.media').media({width:800, height:449});
});
</script>

<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @profil.nom %>
</p>

<p>
  <strong>Description:</strong>
  <%= @profil.description %>
</p>
<p>
<strong>Cours:</strong>

<a class="media" href= "<%=@profil.cours%>" ></a>
</p>

<%= link_to 'Edit', edit_profil_path(@profil) %> |
<%= link_to 'Back', profils_path %>

app/views/profiltotals/index.html.haml
%html
  %head
  %title Mon projet
  %link{:href => "//localhost:3000/assets/css.css", :rel => "stylesheet", :type => "text/css"}
    %body
      %div{:id =>"wrap", :align =>"center"}
        - @profiltotal.each do |profil|
          %div{:id => profil["id"], :class => "test"} 
            %img
              = image_tag profil.avatars(:medium)
            %p{:id=>"test"}
              = profil["email"]
      %div{:id =>"fade"}
        %div{:id =>"pop-up"}
      
      :javascript
        $('#wrap div').click(function() {
          var thisID = $(this).attr('id');
          var thisID1 = $(this).attr('id');
          $.ajax({
            type:"Get",
            url:"/profiltotals/show",
            data:{path:thisID},
            success: function(data){
              $("#pop-up").html(data);
              $("#fade").show();
              $("#pop-up").show();
              $("#fade").click(function(){
               $("#pop-up").hide();
               $("#fade").hide();
              });
              },
            error:function(data){
            console.log(data);
            }
          });
        });

app/views/profiltotals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @profiltotal.first['lastname'] %>
</p>

<p>
  <strong>Description:</strong>
  <%= @profiltotal.first['email'] %>
</p>